[package]
name = "order-book-service"
version = "0.1.0"
edition = "2021"



[[bin]]
path = "src/server.rs"
name="order-book-server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.8.3"
prost = "0.11.6"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.11"

[build-dependencies]
tonic-build = "0.8.4"
